defmodule FEnum.Native do
  use Rustler, otp_app: :f_enum, crate: :f_enum_nif

  # Foundation
  def nif_new(_list), do: :erlang.nif_error(:nif_not_loaded)
  def nif_new_from_binary(_binary), do: :erlang.nif_error(:nif_not_loaded)
  def nif_to_list(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def nif_to_binary(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def nif_length(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def nif_inspect(_resource, _count), do: :erlang.nif_error(:nif_not_loaded)

  # Ordering — Resource (chain)
  def nif_sort_asc(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def nif_sort_desc(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def nif_reverse(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def nif_dedup(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def nif_uniq(_resource), do: :erlang.nif_error(:nif_not_loaded)

  # Ordering — Binary (one-shot)
  def nif_sort_asc_binary(_binary), do: :erlang.nif_error(:nif_not_loaded)
  def nif_sort_desc_binary(_binary), do: :erlang.nif_error(:nif_not_loaded)
  def nif_reverse_binary(_binary), do: :erlang.nif_error(:nif_not_loaded)
  def nif_dedup_binary(_binary), do: :erlang.nif_error(:nif_not_loaded)
  def nif_uniq_binary(_binary), do: :erlang.nif_error(:nif_not_loaded)

  # Aggregation — Resource (chain)
  def nif_sum(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def nif_product(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def nif_min(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def nif_max(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def nif_min_max(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def nif_count(_resource), do: :erlang.nif_error(:nif_not_loaded)

  # Aggregation — Binary (one-shot)
  def nif_sum_binary(_binary), do: :erlang.nif_error(:nif_not_loaded)
  def nif_product_binary(_binary), do: :erlang.nif_error(:nif_not_loaded)
  def nif_min_binary(_binary), do: :erlang.nif_error(:nif_not_loaded)
  def nif_max_binary(_binary), do: :erlang.nif_error(:nif_not_loaded)
  def nif_min_max_binary(_binary), do: :erlang.nif_error(:nif_not_loaded)
  def nif_count_binary(_binary), do: :erlang.nif_error(:nif_not_loaded)

  # Access — Resource (chain)
  def nif_at(_resource, _index), do: :erlang.nif_error(:nif_not_loaded)
  def nif_slice(_resource, _start, _len), do: :erlang.nif_error(:nif_not_loaded)
  def nif_take(_resource, _count), do: :erlang.nif_error(:nif_not_loaded)
  def nif_drop(_resource, _count), do: :erlang.nif_error(:nif_not_loaded)
  def nif_member(_resource, _value), do: :erlang.nif_error(:nif_not_loaded)

  # Access — Binary (one-shot)
  def nif_at_binary(_binary, _index), do: :erlang.nif_error(:nif_not_loaded)
  def nif_slice_binary(_binary, _start, _len), do: :erlang.nif_error(:nif_not_loaded)
  def nif_take_binary(_binary, _count), do: :erlang.nif_error(:nif_not_loaded)
  def nif_drop_binary(_binary, _count), do: :erlang.nif_error(:nif_not_loaded)
  def nif_member_binary(_binary, _value), do: :erlang.nif_error(:nif_not_loaded)

  # Combination — Resource (chain)
  def nif_concat(_resource, _other), do: :erlang.nif_error(:nif_not_loaded)
  def nif_frequencies(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def nif_empty(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def nif_join(_resource, _separator), do: :erlang.nif_error(:nif_not_loaded)
  def nif_with_index(_resource, _offset), do: :erlang.nif_error(:nif_not_loaded)
  def nif_zip(_res1, _res2), do: :erlang.nif_error(:nif_not_loaded)
  def nif_chunk_every(_resource, _count), do: :erlang.nif_error(:nif_not_loaded)

  # Combination — Binary (one-shot)
  def nif_concat_binary(_binary1, _binary2), do: :erlang.nif_error(:nif_not_loaded)
  def nif_frequencies_binary(_binary), do: :erlang.nif_error(:nif_not_loaded)
  def nif_join_binary(_binary, _separator), do: :erlang.nif_error(:nif_not_loaded)
  def nif_with_index_binary(_binary, _offset), do: :erlang.nif_error(:nif_not_loaded)
  def nif_zip_binary(_binary1, _binary2), do: :erlang.nif_error(:nif_not_loaded)
  def nif_chunk_every_binary(_binary, _count), do: :erlang.nif_error(:nif_not_loaded)

  # Legacy list-protocol NIFs
  def nif_sort_asc_list(_list), do: :erlang.nif_error(:nif_not_loaded)
  def nif_sort_desc_list(_list), do: :erlang.nif_error(:nif_not_loaded)
  def nif_reverse_list(_list), do: :erlang.nif_error(:nif_not_loaded)
  def nif_dedup_list(_list), do: :erlang.nif_error(:nif_not_loaded)
  def nif_uniq_list(_list), do: :erlang.nif_error(:nif_not_loaded)
  def nif_sum_list(_list), do: :erlang.nif_error(:nif_not_loaded)
  def nif_product_list(_list), do: :erlang.nif_error(:nif_not_loaded)
  def nif_min_list(_list), do: :erlang.nif_error(:nif_not_loaded)
  def nif_max_list(_list), do: :erlang.nif_error(:nif_not_loaded)
  def nif_min_max_list(_list), do: :erlang.nif_error(:nif_not_loaded)
  def nif_count_list(_list), do: :erlang.nif_error(:nif_not_loaded)
  def nif_at_list(_list, _index), do: :erlang.nif_error(:nif_not_loaded)
  def nif_slice_list(_list, _start, _len), do: :erlang.nif_error(:nif_not_loaded)
  def nif_take_list(_list, _count), do: :erlang.nif_error(:nif_not_loaded)
  def nif_drop_list(_list, _count), do: :erlang.nif_error(:nif_not_loaded)
  def nif_member_list(_list, _value), do: :erlang.nif_error(:nif_not_loaded)
  def nif_concat_list(_list1, _list2), do: :erlang.nif_error(:nif_not_loaded)
  def nif_frequencies_list(_list), do: :erlang.nif_error(:nif_not_loaded)
  def nif_join_list(_list, _separator), do: :erlang.nif_error(:nif_not_loaded)
  def nif_with_index_list(_list, _offset), do: :erlang.nif_error(:nif_not_loaded)
  def nif_zip_list(_list1, _list2), do: :erlang.nif_error(:nif_not_loaded)
  def nif_chunk_every_list(_list, _count), do: :erlang.nif_error(:nif_not_loaded)
end
